### PR TITLE
Hopefully fixed bug on PR #311 (Issue #271.)

### PR DESCRIPTION
**Pull request by mikeschinkel**
Changed SQL query to count replies instead of relying on `post_status='queued'`.

See: https://github.com/Awesome-Support/Awesome-Support/pull/311#issuecomment-220904725

### CODE REVIEW

**Comment by julien731** [comment]
Unfortunately, it doesn't fix the issue :(

image

Left side is with the 2 additional methods commented out, right side with the 2 methods active. Notice ticket 138 missing. Its state is "In Progress" (`queued`) but it has 0 replies.

The tabs at the top of the table always indicate the correct number of tickets (7 in my case) but 138 is missing from the table list.

**Comment by mikeschinkel** [comment]
@julien731  

This does not appear to be the same test data you provided me.  So it seems the problem is that the test data you provided me is not complete?  :-)

I will need a full set of test data otherwise we could both end up spinning our wheels quite a bit here.  So if you find an anomaly please provide an updated test database. Ideally, a README explaining the data that is not working would help too.

**Comment by julien731** [comment]
Indeed, it is not the same data. We only discovered this issue after running pre-release tests so we've been changing the data. Re-creating the issue is quite simple, though. You just need to change the status of any un-replied ticket.

If it's faster for you to import an SQL dump you can use this one (from my dev VVV): http://jmp.sh/T9WZm8q

**Comment by mikeschinkel** [comment]
@julien731 Much less margin for error for you to give me a database than for me to try to make sure I understand the instructions and apply them correctly, so thanks.

Where should the missing post appear in the list, and for what criteria?

**Comment by mikeschinkel** [comment]
@julien731 - I decided to refactor and use a different approach since I was having trouble getting the SQL statement working perfectly, and this approach won't cause any tickets to be lost.  At worse the will be ordered incorrectly, and likely at the top.

My assumption is this will work based on the data that I have.  If you find new data that this does not work with, let me know.

**Comment by julien731** [comment]
All the tickets are back! I'm playing around a bit.

**Comment by julien731** [comment]
So, we've been testing this PR and things look good.

The "global" order is correct:

1. Un-replied tickets
2. Tickets awaiting support reply
3. Tickets awaiting client reply

I have one small issue though with tickets awaiting support reply. The 3 "awaiting support reply" tickets I have aren't displayed in a logical order:

image

- Last replied 1 day ago
- Last replied 1 hour ago
- Last replied 1 day ago

The two first tickets are correctly ordered, but the third one should be before or after the first one.

With that being said, this is not critical. I realize you've spent many hours on this and I certainly don't want to ask for more at this point.

If you see an obvious reason for that that's cool, otherwise, it's no big deal. Having tickets ordered this way is definitely a ton better than before and your work has been absolutely great.

If you don't see anything obvious and don't want to spend more time on this let me know and I'll happily merge your PR.

Just in case, a DB dump is available here: http://jmp.sh/2DMgwed

Again, if you don't have anymore time for this, I'm already super happy with what you've done so don't worry :)

**Comment by mikeschinkel** [comment]
@julien731 Try now?

**Comment by mikeschinkel** [comment]
BTW, you are caching the number of replies displayed in the column using `wp_cache_get()` in `WPAS_Tickets_List->get_replies_query()` but you are not expiring the cache so I am finding results that show _"No Reply Yet"_ that actually do have replies.  

So you should add a timeout.

**Comment by SiamKreative** [comment]
@mikeschinkel I can't thank you enough for all of this! If you ever come to Bangkok, let us buy you a beer :)

@julien731 is out of the country and should be back on Thursday or Friday. Not sure he'll be able to check the latest edits while away.

I'll try those edits myself and let you know the results.

**Comment by mikeschinkel** [comment]
@SiamKreative Glad to help.  Let me know if it (finally) works.

**Comment by julien731** [comment]
Looks good to me.

**Comment by julien731** [comment]
Merged via 5534b63026d7023be7fe2e69f9baca873b2e1774

**Pull request closed without merging**
