### PR TITLE
Added ability to configure autolinker.

### PR DESCRIPTION
**Pull request by nmoinvaz**
This pull requests adds the ability to configure whether or not the autolinker is turned on or off. I turn off autolinker script inclusion based on the `use_autolinker` option. And then in the javascript, I checked to see if the Autolinker object is defined.

### CODE REVIEW

**Comment by elindydotcom** [comment]
One minor change - the desc in the settings screen need to have the 'awesome-support' text domain included in the __ function.

**Comment by nmoinvaz** [comment]
Thanks, change made.

**Comment by nmoinvaz** [comment]
Do you know of an example in the code where you are passing the options to the JS? Maybe that way I can do it how you are currently doing it. I couldn't find any way last time I looked.

**Comment by elindydotcom** [comment]
Take a look at scripts.php (includes/scripts.php).  The calls to wp_localize_script is where we pass in values to that get picked up on the frontend js.

**Comment by nmoinvaz** [comment]
It looks like these changes got overwritten some how. The config option exists, but it doesn't actually work.

**Comment by nmoinvaz** [comment]
Well it exists in this repository but when I updated through Wordpress those changes don't exist.

**Pull request merged**
