### PR TITLE
Move tickets with recent replies to the top (issue #271)

### PR DESCRIPTION
**Pull request by mikeschinkel**

### CODE REVIEW

**Comment by SiamKreative** [comment]
Thanks so much for this @mikeschinkel :+1: 

There is an issue, though. My tickets with the label [In Progress] but no reply disappeared from the ticket list. If I comment those [two lines](https://github.com/Awesome-Support/Awesome-Support/blob/develop/includes/admin/class-admin-tickets-list.php#L31-L32), then I can see those tickets again.

**Comment by julien731** [comment]
My guess is that is comes from the `CASE WHEN {$wpdb->posts}.post_status='queued'` part. The query might assume that a ticket with no replies **has** the `queued` status, which might not be the case (also, status can be customized by the user).

**Comment by mikeschinkel** [comment]
You are correct. Is there any other value in ticket post type that will determine if there are replies? I can `count()` but that might require rewriting the query.

**Comment by julien731** [comment]
Unfortunately, no. There is no indicator of the number of replies or if
there are replies at all.

On Mon, May 23, 2016, 16:46 Mike Schinkel <notifications@github.com> wrote:

> You are correct. Is there any other value in ticket post type that will
> determine if there are replies? I can count() but that might require
> rewriting the query.
>
> —
> You are receiving this because you modified the open/close state.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/Awesome-Support/Awesome-Support/pull/311#issuecomment-220935199>
>
-- 
*Julien Liabeuf*
WordPress Specialist
http://julienliabeuf.com || GitHub <https://github.com/julien731> || Twitter
<https://twitter.com/julien731>
+66(0)8-7703-0926

**Comment by mikeschinkel** [comment]
I will see if I can fix it. But it may have to be a few days.

**Comment by mikeschinkel** [comment]
@SiamKreative @julien731 Assuming the PR passes tests can you test my latest fix?

**Pull request merged**
