### PR TITLE
Improvements to use autolinker option for frontend. 

### PR DESCRIPTION
**Pull request by nmoinvaz**
This should fix the front-end issue described in #671

### CODE REVIEW

**Comment by elindydotcom** [comment]
I merged this in as well.  But I think your goal was to remove the autolinker from all elements on the front-end?  If so, the opening post isn't handled at all.  Just the replies are.  Just wanted to point that out in case you wanted the opening post to be handled as well.

**Comment by nmoinvaz** [comment]
Yeah I wanted the opening post to be handled as well. Did I miss a wp_localize_script instance?

**Comment by elindydotcom** [comment]
I don't think you did. But the opening post seems to be auto-linking no matter what the new setting says.

**Comment by nmoinvaz** [comment]
I am having a hard time duplicating the issue with it showing on the opening post. Are you sure the opening post doesn't have an HTML anchor tag that would cause it to always be linked?

**Pull request merged**
