### PR TITLE
Change link to Attachments

### PR DESCRIPTION
**Pull request by chuckgreenman**
Changed the WPAS built links to a direct link.  Several users are reporting this issue, i'd recommend this more straightforward approach until a proper solution can be found.

### CODE REVIEW

**Comment by elindydotcom** [comment]
@julien731  - I think its fixing a couple of errors like these two:

https://wordpress.org/support/topic/download-of-attachment-downloaded-file-0-kb/
https://wordpress.org/support/topic/attached-image-sometimes-not-displayed-completely/

Maybe the solution would be to add a flag under TICKETS->SETTINGS->ADVANCED to turn on/off the direct URL.

**Comment by cmorbitzer** [comment]
Security by obscurity isn't security. This just takes away the obscurity so that the software actually works.

From that second link:

> Sidenote: Currently it is possible to view attachments by “guessing” filenames, which takes a while, but still is possible. You should probably add some Deny from all rules in a .htaccess in uploads/awesome-support/ folder, similar to some backup plugins. Requires lots of testing though, for all kind of servers…

**Comment by elindydotcom** [comment]
Just pushed a changed to the dev branch offers an option for the type of links.  Also offers an option for the informed/advanced admin to change the contents of the htaccess file protecting the individual ticket upload folders. Both options are now under the TICKETS->SETTINGS->ADVANCED tab. Please test and then we can close this PR.

**Comment by julien731** [comment]
Agreed that security through obscurity is not good, but I don't see how it applies here. We're talking about hiding the direct link to the file, not "hiding" the source code that handles this.

**Comment by elindydotcom** [comment]
I've been unable to duplicate the underlying issue on our test servers.  Neither AWS nor wpengine servers or local dev servers seem to exhibit this issue. So its likely server configuration based and seem to have a permissions message thrown in the error.log file from some of the error-logs sent by users.  The change pushed 5 days ago is a workaround, not a fix for the underlying issue.  If the underlying issue is indeed something related to server configurations then I doubt any code change will "fix" the issue so we'll be stuck with the workaround. @chuckgreenman , @cmorbitzer - have you been able to test the change?

**Pull request closed without merging**
